<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_passwordNew</name>
   <tag></tag>
   <elementGuidId>7ab00531-20c5-4193-ab8e-5fe0c2ee80dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>577464b4-d89e-44e8-b8cb-7ac21eefb36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>561536ee-032c-462b-bd82-6aaa1ecd4dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c89d4ebf-186b-4617-91fe-9e9b9d354b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordNew</value>
      <webElementGuid>85c5cab7-031f-4373-ac69-4665e99baf69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passwordNew</value>
      <webElementGuid>fceb3d12-f0af-4c98-a2ad-a9ece8a4c062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu từ 6 đến 32 ký tự</value>
      <webElementGuid>a3b600bc-9d8b-4be9-95e2-c39696190612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordNew&quot;)</value>
      <webElementGuid>a6d06dfa-b5ee-4421-a9ea-f624365f9701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordNew']</value>
      <webElementGuid>f49b9673-1e89-40d3-a2b4-fffb7cb229f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div[2]/input</value>
      <webElementGuid>86a8efb0-98aa-44cf-98c9-1a42b93dd1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>011c8954-17fa-476c-82da-b43009b64047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'passwordNew' and @name = 'passwordNew' and @placeholder = 'Mật khẩu từ 6 đến 32 ký tự']</value>
      <webElementGuid>c0b33d63-6926-427a-9109-dd8008b8b1fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
