<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Giohang</name>
   <tag></tag>
   <elementGuidId>88eadb03-b5a0-4842-8252-d569a7369fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-addtocart-button > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='product-addtocart-button']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bcdf30f3-4e58-4dba-bc51-f881ee27cbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giỏ hàng</value>
      <webElementGuid>1d641de7-8a25-4240-b982-6bd4ed3606dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-addtocart-button&quot;)/span[1]</value>
      <webElementGuid>b2536504-78b2-4357-80cb-2b07a83b498c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='product-addtocart-button']/span</value>
      <webElementGuid>8f5495e3-2783-4766-93bf-1a476832cd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Còn hàng'])[165]/following::span[1]</value>
      <webElementGuid>10d81c99-448a-4446-bf35-5cbb7e5b1376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trễ tặng 100k'])[1]/preceding::span[1]</value>
      <webElementGuid>d5e4b0e2-a2ea-48bb-a3f2-c63f76449767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Giỏ hàng']/parent::*</value>
      <webElementGuid>b517a7da-5c74-42a2-b211-1390fb1d5fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span</value>
      <webElementGuid>24ff7458-8509-4b61-8309-6d8e6c732299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Giỏ hàng' or . = 'Giỏ hàng')]</value>
      <webElementGuid>e98f1add-8ac9-48fe-a1cb-83f348143eb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
