<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Search</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0630d0f4-cda4-4160-847e-caa663d68fbf</testSuiteGuid>
   <testCaseLink>
      <guid>8c774aff-01f1-4b29-a7de-5f1fc2d87c9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Search</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>752140e3-b2e7-4c08-95fe-9ab7daeec395</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Search</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>752140e3-b2e7-4c08-95fe-9ab7daeec395</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>keywords</value>
         <variableId>9b4a5407-f174-4966-afa2-56655e6e74ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>752140e3-b2e7-4c08-95fe-9ab7daeec395</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Expected</value>
         <variableId>27210023-f04f-44b4-b180-9bc5a29d30ae</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
