<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_ThongTinTaiKhoan</name>
   <tag></tag>
   <elementGuidId>40ff059e-31af-4526-a19e-eab215cf3128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profile_page']/div/div/div[2]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3df46a7-3459-492c-9065-14b83a94d56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hasaki.vn/customer/account/edit</value>
      <webElementGuid>8e442430-459f-4029-893a-a9f424f9f062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item_menu_profile </value>
      <webElementGuid>ab298206-fc56-4a55-b8a8-8c3f2cb6bfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin tài khoản</value>
      <webElementGuid>a369c8d6-f59d-41f3-8f94-5b3582008f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_page&quot;)/div[@class=&quot;col-lg-3 col-md-3  col-sm-3&quot;]/div[@class=&quot;block_menu_profile space_bottom_20&quot;]/div[@class=&quot;menu_profile width_common&quot;]/a[@class=&quot;item_menu_profile&quot;]</value>
      <webElementGuid>abd3a4f4-e2ec-494e-8c2c-3960771dc3f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile_page']/div/div/div[2]/a[3]</value>
      <webElementGuid>6c7ef0e5-c366-455f-9c9e-33a4c7122be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Thông tin tài khoản')])[2]</value>
      <webElementGuid>3d81208c-b880-4258-ad28-a3ee4c85ca74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasaki tích điểm'])[1]/following::a[1]</value>
      <webElementGuid>2dfd4287-46e4-491d-8ae9-521fd3671866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản lý tài khoản'])[1]/following::a[2]</value>
      <webElementGuid>7b7d0070-1fbe-4127-a435-38dcf5b01617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đơn hàng của tôi'])[1]/preceding::a[1]</value>
      <webElementGuid>2b084e8f-1a40-4374-a8d6-51a3d9383554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking của tôi'])[1]/preceding::a[2]</value>
      <webElementGuid>ad36f1af-ed36-492a-a182-111b8f5ebe57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://hasaki.vn/customer/account/edit')])[2]</value>
      <webElementGuid>f830273c-6663-4022-adce-d1a41cf79f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div[2]/a[3]</value>
      <webElementGuid>3bec1d30-fe0c-4907-943b-2784c29cc78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hasaki.vn/customer/account/edit' and (text() = 'Thông tin tài khoản' or . = 'Thông tin tài khoản')]</value>
      <webElementGuid>dca690c1-ccae-45db-ba1d-c3163894b5ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
