<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EnterSearch</name>
   <tag></tag>
   <elementGuidId>b0b558b9-9e16-47e1-a64d-5ff0b2fcb0ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f953c69-68db-4ffb-9a3a-7a149ff0df5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>8fed0794-f4aa-4965-a6f8-d6eaa8721365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Khai trương CN188 Q. Tân Bình, TP. HCM | Deal 5K (Duy nhất 19/05)</value>
      <webElementGuid>2f12e9b4-994e-4d1c-8872-e6cf0b3f25f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_search</value>
      <webElementGuid>17d386b2-6324-4bc4-ae81-ea9332a1aa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>0bb3c47d-2b6b-4a33-b90e-e17944f81864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-box-parent</name>
      <type>Main</type>
      <value>#block_suggest_search</value>
      <webElementGuid>f74788f7-a7a1-4983-9d9f-7a6c89d86410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5602fe22-0df1-4079-a55b-710498e38968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b4c2f72-ef54-499f-93f5-7c1c826f553d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>campaign-rel</name>
      <type>Main</type>
      <value>[{&quot;label&quot;:&quot;Khai trương CN188 Q. Tân Bình, TP. HCM | Deal 5K (Duy nhất 19/05)&quot;,&quot;url&quot;:&quot;https://hasaki.vn/campaign/khai-truong-chi-nhanh-187-188?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=khai-truong-chi-nhanh-187-188&amp;utm_term=khai-truong-chi-nhanh-187-188_16052024&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1716137940,&quot;start_time&quot;:1715792400},{&quot;label&quot;:&quot;Khai trương CN187 TX. Chơn Thành, Bình Phước | Deal 5K (Duy nhất 19/05)&quot;,&quot;url&quot;:&quot;https://hasaki.vn/campaign/khai-truong-chi-nhanh-187-188?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=khai-truong-chi-nhanh-187-188&amp;utm_term=khai-truong-chi-nhanh-187-188_16052024&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1716137940,&quot;start_time&quot;:1715792400},{&quot;label&quot;:&quot;Mua Gì Cũng Rẻ - Dưới 99K&quot;,&quot;url&quot;:&quot;https://hasaki.vn/tag/gi-cung-re.html?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=gi-cung-re&amp;utm_term=gi-cung-re_26032024&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1735664340,&quot;start_time&quot;:1714582800},{&quot;label&quot;:&quot;MỚI - Mút Trang Điểm Kháng Khuẩn Mastige&quot;,&quot;url&quot;:&quot;https://hasaki.vn/thuong-hieu/mastige.html?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=mut-trang-diem-khang-khuan-mastige&amp;utm_term=mut-trang-diem-khang-khuan-mastige_08052024&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1717174740,&quot;start_time&quot;:1715101200},{&quot;label&quot;:&quot;Deal Hot Giảm Hơn 60% DV Trải Nghiệm: Triệt Lông, Trị Mụn, Trị Sẹo Rỗ, Peel, Trẻ Hóa Da&quot;,&quot;url&quot;:&quot;https://hasaki.vn/campaign/trai-nghiem-dich-vu?utm_source=website&amp;utm_medium=keyword_thanh_search&amp;utm_campaign=landingpage_trai_nghiem_dich_vu_17022024&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1735664340,&quot;start_time&quot;:1706720400}]</value>
      <webElementGuid>ae75d2f4-74d5-45f0-a1d1-f86708af7787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)</value>
      <webElementGuid>12d2ff37-42d3-4f31-b4b3-c54a79103b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search']</value>
      <webElementGuid>716f7bba-5a91-4ab6-bb8d-7493caf65dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form']/div[2]/div/div/div/input</value>
      <webElementGuid>02b29c69-9d92-4a61-ac17-979d8510abab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>108ff4db-127c-4160-b706-30096093856c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search' and @placeholder = 'Khai trương CN188 Q. Tân Bình, TP. HCM | Deal 5K (Duy nhất 19/05)' and @name = 'q']</value>
      <webElementGuid>5ab4e3fe-4a70-4c37-b397-b21838b60133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
